#!/bin/bash

install_dotfiles() {
    mkdir -p ~/.{config,local} && \
    git clone https://github.com/slspeek/dotfiles.git ~/.dotfiles && \
    cd ~/.dotfiles && \
    tldr --update && \
    stow -v --dotfiles --adopt . && \
    git restore . 
	if [ -n "$ITSME" ]; then
		./scripts/itsme.sh
	fi
}
    
$ROOTCMD sudo -u $username bash -c "export ITSME=$ITSME; $(declare -f install_dotfiles); install_dotfiles"
    