#!/usr/bin/env bash
set -e

$ROOTCMD sudo -u $username xdg-settings set default-web-browser firefox.desktop

$ROOTCMD update-alternatives --set x-www-browser /usr/bin/firefox
$ROOTCMD update-alternatives --set gnome-www-browser /usr/bin/firefox
