#!/usr/bin/env bash
set -e

function install_nerdfonts() {
    if fc-list | grep 'NerdFont' &> /dev/null; then
        echo "✅ NerdFont is already installed, script is aborted on request"
        exit 0
    fi

    FONT_VERSION="v3.4.0"
    FONT_NAME="JetBrainsMono"
    INSTALL_DIR="/usr/local/share/fonts/NerdFonts"

    echo "➡️ Starting installation of $FONT_NAME Nerd Font ($FONT_VERSION)..."

    if [ ! -d "$INSTALL_DIR" ]; then
        echo "➡️ Creating directory: $INSTALL_DIR"
        sudo mkdir -p "$INSTALL_DIR"
    fi

    echo "➡️ Downloading $FONT_NAME..."
    cd /tmp
    wget -q "https://github.com/ryanoasis/nerd-fonts/releases/download/${FONT_VERSION}/${FONT_NAME}.zip"

    echo "➡️ Extracting..."
    unzip -o "${FONT_NAME}.zip" -d "${FONT_NAME}_unpacked"

    echo "➡️ Moving fonts to $INSTALL_DIR..."
    sudo mv "${FONT_NAME}_unpacked"/*.ttf "$INSTALL_DIR"

    echo "➡️ Refreshing font cache..."
    sudo fc-cache -fv &> /dev/null

    echo "➡️ Cleaning up temporary files..."
    rm "${FONT_NAME}.zip"
    rm -rf "${FONT_NAME}_unpacked"

    echo "✅ $FONT_NAME Nerd Font has been successfully installed system-wide!"
}

$ROOTCMD bash -c "$(declare -f install_nerdfonts); install_nerdfonts"