#!/bin/bash
set -e

version=$(curl -s https://api.github.com/repos/zellij-org/zellij/releases/latest | grep tag_name | cut -d '"' -f 4)
zellij_archive=zellij-x86_64-unknown-linux-musl.tar.gz
$ROOTCMD wget --no-verbose "https://github.com/zellij-org/zellij/releases/download/${version}/${zellij_archive}" -P /tmp
$ROOTCMD tar -xzf "/tmp/${zellij_archive}" -C /usr/local/bin
$ROOTCMD chmod +x /usr/local/bin/zellij
$ROOTCMD rm "/tmp/${zellij_archive}"
