#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

fcopy /usr/local/bin/gnome-mouse-key-toggle.sh
fcopy /usr/local/bin/gnome-dark-theme-toggle.sh

exit $error
