#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

$ROOTCMD sudo -u $username /bin/sh -c 'dbus-run-session -- /usr/local/bin/set-gnome-shortcuts.sh'

exit $error
