#!/bin/bash

install_dotfiles() {
    mkdir -p ~/.{config,local} && \
    git clone https://github.com/slspeek/dotfiles.git ~/.dotfiles && \
    cd ~/.dotfiles && \
    tldr --update && \
    stow -v --dotfiles --adopt . && \
    git restore . 
}
    
$ROOTCMD sudo -u $($ROOTCMD id -nu 1000) bash -c "$(declare -f install_dotfiles); install_dotfiles"
    