#! /bin/bash

# (c) Thomas Lange, 2001-2017, lange@debian.org

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

$ROOTCMD usermod -aG sudo $username
if [ ! -f $target/usr/bin/sudo ]; then
  echo "WARNING. Package sudo is not installed"
fi
