#!/usr/bin/env bash
set -e

$ROOTCMD sudo -u $username sh -c "mkdir -p ~/.config/ && xdg-settings set default-web-browser com.google.Chrome.desktop"

$ROOTCMD update-alternatives --set x-www-browser /usr/bin/google-chrome-stable
$ROOTCMD update-alternatives --set gnome-www-browser /usr/bin/google-chrome-stable

