Name: Annabelle
Description: Gnome desktop met Element, VSCode, ProtonVPN.
Classes:  INSTALL FAIBASE NONFREE WIFI DEBIAN DUTCH CONSOLE_TWEAKS ADVANCED_CLI_TOOLS ANNABELLE GNOME_CORE FIREFOX GNOME_EXTENSIONS ELEMENT VSCODE PROTON_VPN NETSELECT_APT
