Name: Annabelle
Description: Gnome desktop met Element, VSCode, ProtonVPN.
Classes:  INSTALL FAIBASE NONFREE WIFI DEBIAN FASTFETCH DUTCH CONSOLE_TWEAKS ADVANCED_CLI_TOOLS ANNABELLE GNOME FIREFOX GNOME_EXTENSIONS ELEMENT VSCODE PROTON_VPN NETSELECT_APT
