Name: Daniel
Classes:  INSTALL FAIBASE NONFREE WIFI DEBIAN FASTFETCH DUTCH CONSOLE_TWEAKS ADVANCED_CLI_TOOLS STEVEN DANIEL LXDE GNOME_EXTENSIONS FIREFOX DEVELOPER ELEMENT MATTERMOST NEOVIM_USER NETSELECT_APT
