Default: Gnome minimaal demo

Name: Gnome minimaal demo
Classes: INSTALL FAIBASE DEBIAN FASTFETCH DUTCH CONSOLE_TWEAKS TUX GNOME_CORE BACKGROUND FIREFOX KEEPASSXC LIBREOFFICE_WRITER GNOME_EXTENSIONS VLC
