Default: Gnome minimaal

Name: Gnome minimaal met Google Chrome
Classes: INSTALL FAIBASE NONFREE WIFI DEBIAN FASTFETCH DUTCH CONSOLE_TWEAKS BASIC_CLI_TOOLS TUX GNOME_CORE BACKGROUND GOOGLE_CHROME LIBREOFFICE_WRITER PRINTING NETSELECT_APT