Name: Gnome 020
Description: Gnome desktop installatie voor Linux 020
Classes: INSTALL FAIBASE NONFREE WIFI DEBIAN FASTFETCH DUTCH CONSOLE_TWEAKS BASIC_CLI_TOOLS TUX GNOME NEW_TO_GNOME FIREFOX RUSTDESK VLC PRINTING NETSELECT_APT
