Name: Hazel
Classes: INSTALL FAIBASE NONFREE WIFI DEBIAN DUTCH CONSOLE_TWEAKS BASIC_CLI_TOOLS TUX HAZEL GNOME GNOME_EXTENSIONS FIREFOX GOOGLE_CHROME LIBREOFFICE MULTIMEDIA PHOTOGRAPHY GRAPHICS PRINTING NEOVIM_USER NETSELECT_APT
