Name: Steven Light
Classes:  INSTALL FAIBASE NONFREE WIFI DEBIAN FASTFETCH DUTCH CONSOLE_TWEAKS STRESS_TEST GNOME STEVEN BACKGROUND VSCODE FIREFOX BTRFS_ONE ELEMENT ALACRITTY NEOVIM_USER NETSELECT_APT
