Name: Steven
Classes:  INSTALL FAIBASE NONFREE WIFI DEBIAN FASTFETCH DUTCH CONSOLE_TWEAKS STRESS_TEST DEBIAN_MIRROR STEVEN BACKGROUND HYPRLAND GOOGLE_CHROME FIREFOX GNOME DEVELOPER BTRFS_ONE GNOME_EXTENSIONS ELEMENT MATTERMOST ALACRITTY NEOVIM_USER NETSELECT_APT
