Name: Steven
Classes:  INSTALL FAIBASE NONFREE WIFI DEBIAN FASTFETCH DUTCH CONSOLE_TWEAKS STRESS_TEST DEBIAN_MIRROR GNOME STEVEN BACKGROUND HYPRLAND GOOGLE_CHROME FIREFOX DEVELOPER BTRFS_ONE ELEMENT MATTERMOST ALACRITTY NEOVIM_USER NETSELECT_APT
