Name: Steven
Classes:  INSTALL FAIBASE NONFREE WIFI DEBIAN DUTCH CONSOLE_TWEAKS ADVANCED_CLI_TOOLS STEVEN GNOME BACKGROUND FIREFOX DEVELOPER BTRFS_ONE GNOME_EXTENSIONS ELEMENT MATTERMOST DEBIAN_MIRROR NEOVIM_USER NETSELECT_APT
