Name: Steven 020
Classes:  INSTALL FAIBASE NONFREE WIFI DEBIAN DUTCH CONSOLE_TWEAKS ADVANCED_CLI_TOOLS STEVEN GNOME BACKGROUND FIREFOX DEVELOPER GNOME_EXTENSIONS MIRROR DEBIAN_MIRROR NEOVIM_USER NETSELECT_APT
