Name: Steven Light
Classes:  INSTALL FAIBASE NONFREE WIFI DEBIAN FASTFETCH DUTCH CONSOLE_TWEAKS ADVANCED_CLI_TOOLS STRESS_TEST STEVEN BACKGROUND VSCODE HYPRLAND GOOGLE_CHROME FIREFOX GNOME BTRFS_ONE GNOME_EXTENSIONS ELEMENT ALACRITTY NEOVIM_USER NETSELECT_APT
