Name: Steven 020
Description: Developer Gnome desktop 
Short: Developer Gnome desktop  
Long: Developer Gnome desktop met Debian mirror
Classes:  INSTALL FAIBASE NONFREE WIFI DEBIAN DUTCH CONSOLE_TWEAKS ADVANCED_CLI_TOOLS STEVEN GNOME_CORE BACKGROUND FIREFOX DEVELOPER GNOME_EXTENSIONS MIRROR DEBIAN_MIRROR NEOVIM_USER NETSELECT_APT
